Pepper pepper #current best estimate of Fruit and Peduncle. Frame should be in link_base frame

uint8 GRIPPER_PREGRASP_PLAN=1
uint8 GRIPPER_GRASP_PLAN=2
uint8 CUTTER_GRASP_PLAN=3
uint8 GRIPPER_TO_BIN_PLAN=4

uint8 mode #mode of planner (choose one from above)

uint8 GRIPPER_DO_ROTATE_CAMERA=1
uint8 GRIPPER_DO_NOT_ROTATE_CAMERA=2

uint8 gripper_camera_rotation #mode of gripper planner (rotate or do not rotate), choose one from above

float32 reserve_dist # radius (in METERS) that the final pose is, away from the pepper/peduncle center
---
uint8 result