Pepper pepper # Current best estimate of fruit, peduncle

uint8 HOME_CUTTER=1
uint8 HOME_GRIPPER=2
uint8 PARALLEL_MOVE_PREGRASP=3
uint8 GRIPPER_GRASP=4
uint8 CUTTER_GRASP=5
uint8 PARALLEL_MOVE_STORAGE=6



uint8 mode # current plan (choose from above)
---
uint8 success

uint8 result

uint8 SUCCESS = 1
uint8 FAIL_CUTTER_PLAN_DEVIATE_START_STATE=10
uint8 FAIL_CUTTER_PLAN_NO_IK_SOLUTION_FOUND=11
uint8 FAIL_CUTTER_PLAN_RRT_TIMEOUT=12
uint8 FAIL_CUTTER_PLAN_CARTESIAN_FAILED=13
uint8 FAIL_CUTTER_EXECUTE_FAILED=14

uint8 FAIL_GRIPPER_PLAN_DEVIATE_START_STATE=20
uint8 FAIL_GRIPPER_PLAN_NO_IK_SOLUTION_FOUND=21
uint8 FAIL_GRIPPER_PLAN_RRT_TIMEOUT=22
uint8 FAIL_GRIPPER_PLAN_CARTESIAN_FAILED=23
uint8 FAIL_GRIPPER_EXECUTE_FAILED=24
uint8 FAIL_UNKNOWN=255